# Generated by Django 6.1 on 2026-08-31 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={},
        ),
    ]
