# Generated by Django 6.1 on 2026-08-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_crop_options_alter_season_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='base_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='multiharvest',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
