# Generated by Django 6.1 on 2026-09-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_crop_base_price_alter_crop_multiharvest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='base_price',
            new_name='sell_price',
        ),
        migrations.AddField(
            model_name='crop',
            name='days_to_regrow',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_harvest',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='crop',
            name='seed_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FertilizerQualityChance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farming_level', models.IntegerField()),
                ('regular_chance', models.IntegerField()),
                ('silver_chance', models.IntegerField()),
                ('gold_chance', models.IntegerField()),
                ('iridium_chance', models.IntegerField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fertilizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fertilizer')),
            ],
        ),
    ]
