# Generated by Django 6.1 on 2026-09-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_base_price_crop_sell_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertilizer',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Quality', 'Quality'), ('Deluxe', 'Deluxe')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=50, unique=True),
        ),
    ]
