# Generated by Django 6.1 on 2026-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fertilizer_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='special_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
