# Generated by Django 6.1 on 2026-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_crop_special_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='special_location',
            field=models.CharField(max_length=100),
        ),
    ]
